name: develop

on:
  push:
    branches:
      - 'v0.5.0'
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        yarn install
        yarn test-all
    - name: build
      run: |
        yarn build-app
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/app/
        destination_dir: develop/
