name: purescript

on:
  push:
    paths-ignore:
    - 'old/**'
    - '**/README.md'
  pull_request:
    paths-ignore:
    - 'old/**'
    - '**/README.md'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        yarn install
        yarn run bundle-tests
        yarn run tests

  deploy:
    runs-on: ubuntu-18.04
    needs: test
    if: github.ref == 'refs/heads/release'
    steps:
    - name: deploy
      run: |
        yarn install
        yarn run deploy-app
