name: purescript

on:
  push:
    paths-ignore:
    - 'old'
  pull_request:
    paths-ignore:
    - 'old'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        cd new
        yarn install
        yarn run bundle
        yarn run test
