name: purescript

on:
  push:
    branches:
      - github-build # for now

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        sudo npm install --unsafe-perm purescript spago -g
        cd purescript && sudo spago build && sudo spago test
