name: purescript

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      # ouch, probably a way to avoid these permissions hacks
      run: |
        sudo npm install --unsafe-perm purescript spago -g
        cd purescript && sudo spago build && sudo spago test
