name: typescript

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        sudo npm install karma -g
        cd old && yarn install
        yarn run test
#        sudo npm install karma -g
#        cd old && npm install
#        npm test
