name: v0.3.1-typescript

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday at midnight UTC
  push:
    branches:
      - 'v0.3.1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: unzip # no longer builds -- unzip prebuilt archive
      run: |
        set -x -e
        unzip 0.3.1.zip
    - name: gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: 0.3.1
        destination_dir: 0.3.1/
